// Riot Data Dragon 16.16.1 Official Mappings (Champions, Items, Runes, Spells)
var CHAMP_EN_MAP = {
  "아트록스": "Aatrox",
  "아리": "Ahri",
  "아칼리": "Akali",
  "아크샨": "Akshan",
  "알리스타": "Alistar",
  "암베사": "Ambessa",
  "아무무": "Amumu",
  "애니비아": "Anivia",
  "애니": "Annie",
  "아펠리오스": "Aphelios",
  "애쉬": "Ashe",
  "아우렐리온 솔": "Aurelion Sol",
  "오로라": "Aurora",
  "아지르": "Azir",
  "바드": "Bard",
  "벨베스": "Bel'Veth",
  "블리츠크랭크": "Blitzcrank",
  "브랜드": "Brand",
  "브라움": "Braum",
  "브라이어": "Briar",
  "케이틀린": "Caitlyn",
  "카밀": "Camille",
  "카시오페아": "Cassiopeia",
  "초가스": "Cho'Gath",
  "코르키": "Corki",
  "다리우스": "Darius",
  "다이애나": "Diana",
  "드레이븐": "Draven",
  "문도 박사": "Dr. Mundo",
  "에코": "Ekko",
  "엘리스": "Elise",
  "이블린": "Evelynn",
  "이즈리얼": "Ezreal",
  "피들스틱": "Fiddlesticks",
  "피오라": "Fiora",
  "피즈": "Fizz",
  "갈리오": "Galio",
  "갱플랭크": "Gangplank",
  "가렌": "Garen",
  "나르": "Gnar",
  "그라가스": "Gragas",
  "그레이브즈": "Graves",
  "그웬": "Gwen",
  "헤카림": "Hecarim",
  "하이머딩거": "Heimerdinger",
  "흐웨이": "Hwei",
  "일라오이": "Illaoi",
  "이렐리아": "Irelia",
  "아이번": "Ivern",
  "잔나": "Janna",
  "자르반 4세": "Jarvan IV",
  "잭스": "Jax",
  "제이스": "Jayce",
  "진": "Jhin",
  "징크스": "Jinx",
  "카이사": "Kai'Sa",
  "칼리스타": "Kalista",
  "카르마": "Karma",
  "카서스": "Karthus",
  "카사딘": "Kassadin",
  "카타리나": "Katarina",
  "케일": "Kayle",
  "케인": "Kayn",
  "케넨": "Kennen",
  "카직스": "Kha'Zix",
  "킨드레드": "Kindred",
  "클레드": "Kled",
  "코그모": "Kog'Maw",
  "크산테": "K'Sante",
  "르블랑": "LeBlanc",
  "리 신": "Lee Sin",
  "레오나": "Leona",
  "릴리아": "Lillia",
  "리산드라": "Lissandra",
  "로크": "Locke",
  "루시안": "Lucian",
  "룰루": "Lulu",
  "럭스": "Lux",
  "말파이트": "Malphite",
  "말자하": "Malzahar",
  "마오카이": "Maokai",
  "마스터 이": "Master Yi",
  "멜": "Mel",
  "밀리오": "Milio",
  "미스 포츈": "Miss Fortune",
  "오공": "Wukong",
  "모데카이저": "Mordekaiser",
  "모르가나": "Morgana",
  "나피리": "Naafiri",
  "나미": "Nami",
  "나서스": "Nasus",
  "노틸러스": "Nautilus",
  "니코": "Neeko",
  "니달리": "Nidalee",
  "닐라": "Nilah",
  "녹턴": "Nocturne",
  "누누와 윌럼프": "Nunu & Willump",
  "올라프": "Olaf",
  "오리아나": "Orianna",
  "오른": "Ornn",
  "판테온": "Pantheon",
  "뽀삐": "Poppy",
  "파이크": "Pyke",
  "키아나": "Qiyana",
  "퀸": "Quinn",
  "라칸": "Rakan",
  "람머스": "Rammus",
  "렉사이": "Rek'Sai",
  "렐": "Rell",
  "레나타 글라스크": "Renata Glasc",
  "레넥톤": "Renekton",
  "렝가": "Rengar",
  "리븐": "Riven",
  "럼블": "Rumble",
  "라이즈": "Ryze",
  "사미라": "Samira",
  "세주아니": "Sejuani",
  "세나": "Senna",
  "세라핀": "Seraphine",
  "세트": "Sett",
  "샤코": "Shaco",
  "쉔": "Shen",
  "쉬바나": "Shyvana",
  "신지드": "Singed",
  "사이온": "Sion",
  "시비르": "Sivir",
  "스카너": "Skarner",
  "스몰더": "Smolder",
  "소나": "Sona",
  "소라카": "Soraka",
  "스웨인": "Swain",
  "사일러스": "Sylas",
  "신드라": "Syndra",
  "탐 켄치": "Tahm Kench",
  "탈리야": "Taliyah",
  "탈론": "Talon",
  "타릭": "Taric",
  "티모": "Teemo",
  "쓰레쉬": "Thresh",
  "트리스타나": "Tristana",
  "트런들": "Trundle",
  "트린다미어": "Tryndamere",
  "트위스티드 페이트": "Twisted Fate",
  "트위치": "Twitch",
  "우디르": "Udyr",
  "우르곳": "Urgot",
  "바루스": "Varus",
  "베인": "Vayne",
  "베이가": "Veigar",
  "벨코즈": "Vel'Koz",
  "벡스": "Vex",
  "바이": "Vi",
  "비에고": "Viego",
  "빅토르": "Viktor",
  "블라디미르": "Vladimir",
  "볼리베어": "Volibear",
  "워윅": "Warwick",
  "자야": "Xayah",
  "제라스": "Xerath",
  "신 짜오": "Xin Zhao",
  "야스오": "Yasuo",
  "요네": "Yone",
  "요릭": "Yorick",
  "유나라": "Yunara",
  "유미": "Yuumi",
  "자헨": "Zaahen",
  "자크": "Zac",
  "제드": "Zed",
  "제리": "Zeri",
  "직스": "Ziggs",
  "질리언": "Zilean",
  "조이": "Zoe",
  "자이라": "Zyra",
  "장화": "Boots",
  "요정의 부적": "Faerie Charm",
  "원기 회복의 구슬": "Rejuvenation Bead",
  "거인의 허리띠": "Giant's Belt",
  "민첩성의 망토": "Cloak of Agility",
  "방출의 마법봉": "Blasting Wand",
  "사파이어 수정": "Sapphire Crystal",
  "루비 수정": "Ruby Crystal",
  "천 갑옷": "Cloth Armor",
  "쇠사슬 조끼": "Chain Vest",
  "마법무효화의 망토": "Null-Magic Mantle",
  "잉걸불 칼": "Emberknife",
  "롱소드": "Long Sword",
  "곡괭이": "Pickaxe",
  "B.F. 대검": "B. F. Sword",
  "빗발칼날": "Hailblade",
  "흑요석 검": "Obsidian Edge",
  "단검": "Dagger",
  "곡궁": "Recurve Bow",
  "증폭의 고서": "Amplifying Tome",
  "흡혈의 낫": "Vampiric Scepter",
  "도란의 방패": "Doran's Shield",
  "도란의 검": "Doran's Blade",
  "도란의 반지": "Doran's Ring",
  "음전자 망토": "Negatron Cloak",
  "쓸데없이 큰 지팡이": "Needlessly Large Rod",
  "암흑의 인장": "Dark Seal",
  "수확의 낫": "Cull",
  "도란의 활": "Doran's Bow",
  "퀘스트: 상단": "Quest: Top",
  "퀘스트: 중단": "Quest: Mid",
  "퀘스트: 하단": "Quest: Bot",
  "퀘스트: 서포터": "Quest: Support",
  "퀘스트: 정글": "Quest: Jungle",
  "새끼 화염발톱": "Scorchclaw Pup",
  "새끼 바람돌이": "Gustwalker Hatchling",
  "새끼 이끼쿵쿵이": "Mosstomper Seedling",
  "전령의 눈": "Eye of the Herald",
  "자르반 1세의": "Jarvan I's",
  "도란의 투구": "Doran's Helm",
  "상단 공격로 퀘스트": "Top Lane Quest",
  "중단 공격로 퀘스트": "Mid Lane Quest",
  "하단 공격로 퀘스트": "Bot Lane Quest",
  "서포터 퀘스트": "Support Quest",
  "정글 퀘스트": "Jungle Quest",
  "정글 퀘스트 보상": "Jungle Quest Reward",
  "중단 공격로 퀘스트 보상": "Mid Lane Quest Reward",
  "하단 공격로 퀘스트 보상": "Bot Lane Quest Reward",
  "서포터 퀘스트 보상": "Support Quest Reward",
  "강력 순간이동 (상단 공격로 퀘스트 보상)": "Unleashed Teleport (Top Lane Quest Reward)",
  "상단 공격로 퀘스트 보상": "Top Lane Quest Reward",
  "파멸의식 고서": "Rite Of Ruin",
  "꽃피는 새벽의 검": "Sword of Blossoming Dawn",
  "오만": "Hubris",
  "관통 탄환": "Penetrating Bullets",
  "요새화": "Fortification",
  "이중 갑옷": "Reinforced Armor",
  "파수꾼의 눈": "Warden's Eye",
  "수호자": "Guardian",
  "과충전": "Overcharged",
  "방탄 양말": "Anti-tower Socks",
  "체질": "Gusto",
  "특이 체질": "Phreakish Gusto",
  "슈퍼 메크 방어구": "Super Mech Armor",
  "슈퍼 메크 전력장": "Super Mech Power Field",
  "포탑 방패": "Turret Plating",
  "구조물 현상금": "Structure Bounty",
  "과충전HA": "OvererchargedHA",
  "포탑 강화": "Tower Power-Up",
  "과잉성장": "Overgrowth",
  "귀환": "Recall",
  "상급 귀환": "Enhanced Recall",
  "체력 물약": "Health Potion",
  "귀환 비활성화": "Disabled Recall",
  "": "",
  "굳건한 의지의 완전한 비스킷": "Total Biscuit of Everlasting Will",
  "키르히아이스의 파편": "Kircheis Shard",
  "강철 인장": "Steel Sigil",
  "야수화": "The Brutalizer",
  "땅굴 채굴기": "Tunneler",
  "빛나는 티끌": "Glowing Mote",
  "충전형 물약": "Refillable Potion",
  "부패 물약": "Corrupting Potion",
  "수호자의 부적": "Guardian's Amulet",
  "수호자의 장막": "Guardian's Shroud",
  "수호자의 뿔피리": "Guardian's Horn",
  "포로 간식": "Poro-Snax",
  "제어 와드": "Control Ward",
  "투명 와드": "Stealth Ward",
  "슈렐리아의 군가": "Shurelya's Battlesong",
  "강철의 영약": "Elixir of Iron",
  "마법의 영약": "Elixir of Sorcery",
  "분노의 영약": "Elixir of Wrath",
  "카파 주스": "Cappa Juice",
  "힘의 주스": "Juice of Power",
  "활력의 주스": "Juice of Vitality",
  "가속의 주스": "Juice of Haste",
  "행운의 주사위": "Lucky Dice",
  "향상된 행운의 주사위": "Enhanced Lucky Dice",
  "증강 레벨": "Augment Level",
  "숙련의 영약": "Elixir of Skill",
  "탐욕의 영약": "Elixir of Avarice",
  "힘의 영약": "Elixir of Force",
  "힘의 밴들 주스": "Bandle Juice of Power",
  "활력의 밴들 주스": "Bandle Juice of Vitality",
  "가속의 밴들 주스": "Bandle Juice of Haste",
  "추가 능력치": "Stat Bonus",
  "전설 전사 아이템": "Legendary Fighter Item",
  "전설 원거리 딜러 아이템": "Legendary Marksman Item",
  "전설 암살자 아이템": "Legendary Assassin Item",
  "전설 마법사 아이템": "Legendary Mage Item",
  "전설 탱커 아이템": "Legendary Tank Item",
  "전설 서포터 아이템": "Legendary Support Item",
  "프리즘 아이템": "Prismatic Item",
  "모루 교환권": "Anvil Voucher",
  "골드 능력치 모루 교환권": "Gold Stat Anvil Voucher",
  "프리즘 능력치 모루 교환권": "Prismatic Stat Voucher",
  "용기 교환권": "Bravery Voucher",
  "파편검": "Shardblade",
  "끝없는 절망": "Unending Despair",
  "어둠불꽃 횃불": "Blackfire Torch",
  "케이닉 루컨": "Kaenic Rookern",
  "황혼과 새벽": "Dusk and Dawn",
  "악마사냥꾼의 화살": "Fiendhunter Bolts",
  "끝없는 갈망": "Endless Hunger",
  "실체화 장비": "Actualizer",
  "마법광학 장치 C44": "Hexoptics C44",
  "밴들파이프": "Bandlepipes",
  "원형질 안전벨트": "Protoplasm Harness",
  "속삭이는 머리띠": "Whispering Circlet",
  "악곡의 왕관": "Diadem of Songs",
  "저녁갑주": "Evenshroud",
  "개척자": "Trailblazer",
  "대천사의 지팡이": "Archangel's Staff",
  "마나무네": "Manamune",
  "유령 배회자": "Ghostcrawlers",
  "광전사의 군화": "Berserker's Greaves",
  "탐욕의 군화": "Gluttonous Greaves",
  "신속의 장화": "Boots of Swiftness",
  "화학공학 부패기": "Chemtech Putrifier",
  "마법사의 신발": "Sorcerer's Shoes",
  "수호 천사": "Guardian Angel",
  "무한의 대검": "Infinity Edge",
  "윤 탈 야생화살": "Yun Tal Wildarrows",
  "필멸자의 운명": "Mortal Reminder",
  "도미닉 경의 인사": "Lord Dominik's Regards",
  "아트마의 심판": "Atma's Reckoning",
  "대천사의 포옹": "Seraph's Embrace",
  "무라마나": "Muramana",
  "유령 무희": "Phantom Dancer",
  "판금 장화": "Plated Steelcaps",
  "지크의 융합": "Zeke's Convergence",
  "스테락의 도전": "Sterak's Gage",
  "광휘의 검": "Sheen",
  "정령의 형상": "Spirit Visage",
  "점화석": "Kindlegem",
  "태양불꽃 방패": "Sunfire Aegis",
  "공허의 불길": "Void Immolation",
  "칠흑의 양날 도끼": "The Black Cleaver",
  "피바라기": "The Bloodthirster",
  "실험적 마공학판": "Experimental Hexplate",
  "굶주린 히드라": "Ravenous Hydra",
  "가시 갑옷": "Thornmail",
  "삼위일체": "Trinity Force",
  "강철심장": "Heartsteel",
  "루난의 허리케인": "Runaan's Hurricane",
  "스태틱의 단검": "Statikk Shiv",
  "라바돈의 죽음모자": "Rabadon's Deathcap",
  "마법사의 최후": "Wit's End",
  "고속 연사포": "Rapid Firecannon",
  "폭풍갈퀴": "Stormrazor",
  "리치베인": "Lich Bane",
  "밴시의 장막": "Banshee's Veil",
  "군단의 방패": "Aegis of the Legion",
  "구원": "Redemption",
  "기사의 맹세": "Knight's Vow",
  "얼어붙은 심장": "Frozen Heart",
  "헤르메스의 발걸음": "Mercury's Treads",
  "수호자의 보주": "Guardian's Orb",
  "내셔의 이빨": "Nashor's Tooth",
  "라일라이의 수정홀": "Rylai's Crystal Scepter",
  "악의": "Malignance",
  "혹한의 손길": "Winter's Approach",
  "종말의 겨울": "Fimbulwinter",
  "구인수의 격노검": "Guinsoo's Rageblade",
  "공허의 지팡이": "Void Staff",
  "무덤꽃": "Cryptbloom",
  "헤르메스의 시미터": "Mercurial Scimitar",
  "요우무의 유령검": "Youmuu's Ghostblade",
  "란두인의 예언": "Randuin's Omen",
  "마법공학 총검": "Hextech Gunblade",
  "마법공학 로켓 벨트": "Hextech Rocketbelt",
  "몰락한 왕의 검": "Blade of The Ruined King",
  "맬모셔스의 아귀": "Maw of Malmortius",
  "존야의 모래시계": "Zhonya's Hourglass",
  "명석함의 아이오니아 장화": "Ionian Boots of Lucidity",
  "쇼진의 창": "Spear of Shojin",
  "모렐로노미콘": "Morellonomicon",
  "서풍": "Zephyr",
  "수호자의 검": "Guardian's Blade",
  "선체파괴자": "Hullbreaker",
  "수호자의 망치": "Guardian's Hammer",
  "수호자의 단검": "Guardian's Dirk",
  "강철의 솔라리 펜던트": "Locket of the Iron Solari",
  "가고일 돌갑옷": "Gargoyle Stoneplate",
  "미카엘의 축복": "Mikael's Blessing",
  "경계": "Terminus",
  "불타는 향로": "Ardent Censer",
  "정수 약탈자": "Essence Reaver",
  "망자의 갑옷": "Dead Man's Plate",
  "거대한 히드라": "Titanic Hydra",
  "밤의 끝자락": "Edge of Night",
  "망령 해적검": "Spectral Cutlass",
  "제국의 명령": "Imperial Mandate",
  "대자연의 힘": "Force of Nature",
  "황금 뒤집개": "Golden Spatula",
  "지평선의 초점": "Horizon Focus",
  "우주의 추진력": "Cosmic Drive",
  "균열 생성기": "Riftmaker",
  "밤의 수확자": "Night Harvester",
  "악마의 포옹": "Demonic Embrace",
  "부서진 여왕의 왕관": "Crown of the Shattered Queen",
  "그림자불꽃": "Shadowflame",
  "폭풍 쇄도": "Stormsurge",
  "은빛 여명": "Silvermere Dawn",
  "죽음의 무도": "Death's Dance",
  "화공 펑크 사슬검": "Chempunk Chainsword",
  "갈라진 하늘": "Sundered Sky",
  "흐르는 물의 지팡이": "Staff of Flowing Water",
  "월석 재생기": "Moonstone Renewer",
  "헬리아의 메아리": "Echoes of Helia",
  "새벽심장": "Dawncore",
  "선혈포식자": "Goredrinker",
  "발걸음 분쇄기": "Stridebreaker",
  "신성한 파괴자": "Divine Sunderer",
  "리안드리의 고뇌": "Liandry's Anguish",
  "루덴의 메아리": "Luden's Echo",
  "만년서리": "Everfrost",
  "영겁의 지팡이": "Rod of Ages",
  "얼어붙은 건틀릿": "Iceborn Gauntlet",
  "공허한 광휘": "Hollow Radiance",
  "해신 작쇼": "Jak'Sho, The Protean",
  "광휘의 미덕": "Radiant Virtue",
  "돌풍": "Galeforce",
  "크라켄 학살자": "Kraken Slayer",
  "불멸의 철갑궁": "Immortal Shieldbow",
  "나보리 명멸검": "Navori Flickerblade",
  "징수의 총": "The Collector",
  "드락사르의 황혼검": "Duskblade of Draktharr",
  "월식": "Eclipse",
  "자객의 발톱": "Prowler's Claw",
  "세릴다의 원한": "Serylda's Grudge",
  "독사의 송곳니": "Serpent's Fang",
  "원칙의 원형낫": "Axiom Arc",
  "불경한 히드라": "Profane Hydra",
  "벼락폭풍검": "Voltaic Cyclosword",
  "기회": "Opportunity",
  "증오의 사슬": "Anathema's Chains",
  "우글렛의 마녀 모자": "Wooglet's Witchcap",
  "죽음의 검": "Deathblade",
  "적응형 투구": "Adaptive Helm",
  "흑요석 양날 도끼": "Obsidian Cleaver",
  "핏빛 칼날": "Sanguine Blade",
  "룬 글레이브": "Runeglaive",
  "다용도 도구": "Multitool",
  "심연의 가면": "Abyssal Mask",
  "미니언 해체분석기": "Minion Dematerializer",
  "추적자의 팔목 보호대": "Seeker's Armguard",
  "부서진 팔목 보호대": "Shattered Armguard",
  "약간 신비한 신발": "Slightly Magical Footwear",
  "지배자의 피갑옷": "Overlord's Bloodmail",
  "운명의 재": "Fated Ashes",
  "요새파괴자": "Bastionbreaker",
  "공생형 밑창": "Symbiotic Soles",
  "축복의 성배": "Chalice of Blessing",
  "하나 된 영혼": "Synchronized Souls",
  "생명의 샘 펜던트": "Lifewell Pendant",
  "얼음 방패": "Glacial Buckler",
  "최후의 속삭임": "Last Whisper",
  "메자이의 영혼약탈자": "Mejai's Soulstealer",
  "탐식의 망치": "Phage",
  "온기가 필요한 자의 도끼": "Hearthbound Axe",
  "비상의 월갑": "Winged Moonplate",
  "여신의 눈물": "Tear of the Goddess",
  "덤불 조끼": "Bramble Vest",
  "티아맷": "Tiamat",
  "파수꾼의 갑옷": "Warden's Mail",
  "워모그의 갑옷": "Warmog's Armor",
  "열정의 검": "Zeal",
  "과거 아이템": "Deprecated item",
  "악마의 마법서": "Fiendish Codex",
  "에테르 환영": "Aether Wisp",
  "금지된 우상": "Forbidden Idol",
  "기동력의 장화": "Boots of Mobility",
  "처형인의 대검": "Executioner's Calling",
  "죽음불꽃 손아귀": "Deathfire Grasp",
  "신성의 검": "Sword of the Divine",
  "콜필드의 전투 망치": "Caulfield's Warhammer",
  "톱날 단검": "Serrated Dirk",
  "수은 장식띠": "Quicksilver Sash",
  "정찰병의 새총": "Scout's Slingshot",
  "마법공학 교류 발전기": "Hextech Alternator",
  "기괴한 가면": "Haunting Guise",
  "주문포식자": "Hexdrinker",
  "불멸의 길": "Immortal Path",
  "신속행진": "Swiftmarch",
  "핏빛 명석함": "Crimson Lucidity",
  "건메탈 군화": "Gunmetal Greaves",
  "사슬끈 분쇄자": "Chainlaced Crushers",
  "무장 진격": "Armored Advance",
  "주문투척자의 신발": "Spellslinger's Shoes",
  "영원한 전진": "Forever Forward",
  "그림자 검": "Umbral Glaive",
  "망령의 두건": "Spectre's Cowl",
  "허수아비": "Scarecrow Effigy",
  "비전 탐지기": "Arcane Sweeper",
  "광휘의 특이점": "Lucent Singularity",
  "망원형 개조": "Farsight Alteration",
  "예언자의 렌즈": "Oracle Lens",
  "작은 파티 선물": "Small Party Favor",
  "파티 선물": "Party Favor",
  "수당": "Your Cut",
  "칼리스타의 칠흑의 창": "Kalista's Black Spear",
  "수정 팔 보호구": "Crystalline Bracer",
  "사라진 양피지": "Lost Chapter",
  "억겁의 카탈리스트": "Catalyst of Aeons",
  "주문도둑의 검": "Spellthief's Edge",
  "얼음 송곳니": "Frostfang",
  "얼음 정수의 파편": "Shard of True Ice",
  "강철 어깨 보호대": "Steel Shoulderguards",
  "룬 강철 어깨 갑옷": "Runesteel Spaulders",
  "화이트록의 갑옷": "Pauldrons of Whiterock",
  "고대유물 방패": "Relic Shield",
  "타곤 산의 방패": "Targon's Buckler",
  "타곤 산의 방벽": "Bulwark of the Mountain",
  "영혼의 낫": "Spectral Sickle",
  "해로윙 초승달낫": "Harrowing Crescent",
  "검은 안개 낫": "Black Mist Scythe",
  "세계 지도집": "World Atlas",
  "룬 나침반": "Runic Compass",
  "세계의 결실": "Bounty of Worlds",
  "천상의 이의": "Celestial Opposition",
  "꿈 생성기": "Dream Maker",
  "자자크의 세계가시": "Zaz'Zak's Realmspike",
  "태양의 썰매": "Solstice Sleigh",
  "피의 노래": "Bloodsong",
  "<rarityLegendary>가차없는 포격</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>": "<rarityLegendary>Fire at Will</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "<rarityLegendary>죽음의 여신</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>": "<rarityLegendary>Death's Daughter</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "<rarityLegendary>사기진작</rarityLegendary><br><subtitleLeft><silver>바다뱀 은화 500닢</silver></subtitleLeft>": "<rarityLegendary>Raise Morale</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "망각의 구": "Oblivion Orb",
  "생명선": "Lifeline",
  "핏빛 저주": "Bloodletter's Curse",
  "죄악 포식자": "Sin Eater",
  "번개 끈": "Lightning Braid",
  "얼어붙은 망치": "Frozen Mallet",
  "당혹": "Perplexity",
  "무언의 서약": "Wordless Promise",
  "지옥불 손도끼": "Hellfire Hatchet",
  "활력증진의 펜던트": "Innervating Locket",
  "흑강철 발톱": "Darksteel Talons",
  "질책": "Fulmination",
  "불사대마왕의 왕관": "Demon King's Crown",
  "용암의 방패": "Shield of Molten Stone",
  "별빛밤 망토": "Cloak of Starry Night",
  "엔트로피의 힘": "Force Of Entropy",
  "핏빛 선물": "Sanguine Gift",
  "일라이자의 기적": "Eleisa's Miracle",
  "승천의 부적": "Talisman Of Ascension",
  "불귀신": "Hamstringer",
  "터보 화공 탱크": "Turbo Chemtank",
  "쌍둥이 가면": "Twin Mask",
  "마공화살 동료": "Hexbolt Companion",
  "사신의 대가": "Reaper's Toll",
  "신기루 검": "Mirage Blade",
  "도박꾼의 칼날": "Gambler's Blade",
  "현실 균열": "Reality Fracture",
  "혈마법사의 투구": "Hemomancer's Helm",
  "창공의 서약": "Empyrean Promise",
  "용의 심장": "Dragonheart",
  "참수자": "Decapitator",
  "룬 조각기": "Runecarver",
  "잔혹 행위": "Cruelty",
  "달빛 마법검": "Moonflair Spellblade",
  "살점포식자": "Flesheater",
  "폭발의 구": "Detonation Orb",
  "반향": "Reverberation",
  "섭정 시해": "Regicide",
  "킨코우 십수": "Kinkou Jitte",
  "화염술사의 망토": "Pyromancer's Cloak",
  "번개 막대": "Lightning Rod",
  "다이아몬드 창": "Diamond-Tipped Spear",
  "황혼의 끝자락": "Twilight's Edge",
  "블랙홀 건틀릿": "Black Hole Gauntlet",
  "조종의 손아귀": "Puppeteer",
  "역병의 보석": "Blighting Jewel",
  "신록의 장벽": "Verdant Barrier",
  "흡수의 시선": "Leeching Leer",
  "감시하는 와드석": "Watchful Wardstone",
  "고무의 와드석": "Stirring Wardstone",
  "밴들유리 거울": "Bandleglass Mirror",
  "경계의 와드석": "Vigilant Wardstone",
  "체력 바 색칠: 파랑": "Healthbar Splash: Blue",
  "체력 바 색칠: 주황": "Healthbar Splash: Orange",
  "체력 바 색칠: 초록": "Healthbar Splash: Green",
  "체력 바 색칠: 분홍": "Healthbar Splash: Pink",
  "체력 바 청소: 색상 초기화": "Healthbar Cleanup: Reset Color",
  "체력 바 색칠: 무지개": "Healthbar Splash: Rainbow",
  "강철가시 채찍": "Ironspike Whip",
  "베이가의 승천의 부적": "Veigar's Talisman of Ascension",
  "리안드리의 고통": "Liandry's Torment",
  "바미의 불씨": "Bami's Cinder",
  "절정의 화살": "Noonquiver",
  "분노의 칼": "Rageknife",
  "꽁지깃": "Rectrix",
  "라코어의 방패": "Shield of the Rakkor",
  "전방 정찰": "Scouting Ahead",
  "갱플랭크 Placeholder": "Gangplank Placeholder",
  "속도의 장화": "Boots of Speed",
  "사냥꾼의 마체테": "Hunter's Machete",
  "싸움꾼의 장갑": "Brawler's Gloves",
  "정령석": "Spirit Stone",
  "마나 물약": "Mana Potion",
  "원기회복의 완전한 비스킷": "Total Biscuit of Rejuvenation",
  "불굴의 영약": "Elixir of Fortitude",
  "민첩의 영약": "Elixir of Agility",
  "지능의 영약": "Elixir of Brilliance",
  "수정 플라스크": "Crystalline Flask",
  "예언자의 영약": "Oracle's Elixir",
  "투명 감지 와드": "Vision Ward",
  "시야 와드": "Sight Ward",
  "루비 시야석": "Ruby Sightstone",
  "시야석": "Sightstone",
  "탐험가의 와드": "Explorer's Ward",
  "심연의 홀": "Abyssal Scepter",
  "아트마의 창": "Atma's Impaler",
  "수호자 카탈리스트": "Catalyst the Protector",
  "쌍둥이 그림자": "Twin Shadows",
  "빙하의 장막": "Glacial Shroud",
  "조화의 성배": "Chalice of Harmony",
  "마나의 보주": "Mana Manipulator",
  "닌자의 신발": "Ninja Tabi",
  "스타크의 열정": "Stark's Fervor",
  "용맹의 징표": "Emblem of Valor",
  "저항 공성기": "Ohmwrecker",
  "지휘관의 깃발": "Banner of Command",
  "영혼의 갑옷": "Soul Shroud",
  "태양불꽃 망토": "Sunfire Cape",
  "슈렐리아의 몽상": "Shurelya's Reverie",
  "태양불꽃 망토 무더기": "Stack of Sunfire Capes",
  "탐욕의 검": "Avarice Blade",
  "현자의 돌": "Philosopher's Stone",
  "행운 피크": "Lucky Pick",
  "쐐기검": "Stinger",
  "마드레드의 갈퀴손": "Madred's Razors",
  "룬 방벽": "Runic Bulwark",
  "마드레드의 피갈퀴손": "Madred's Bloodrazor",
  "역병의 비수": "Malady",
  "황금의 심장": "Heart of Gold",
  "레비아탄 갑옷": "Leviathan",
  "비술의 검": "Sword of the Occult",
  "빌지워터 해적검": "Bilgewater Cutlass",
  "마법공학 리볼버": "Hextech Revolver",
  "고대인의 의지": "Will of the Ancients",
  "리글의 랜턴": "Wriggle's Lantern",
  "야생의 섬광": "Feral Flare",
  "슈세이의 마나 통": "Shushei's Mana Jug",
  "이온 충격기": "Ionic Spark",
  "망령의 영혼": "Spirit of the Spectral Wraith",
  "고대 골렘의 영혼": "Spirit of the Ancient Golem",
  "도마뱀 장로의 영혼": "Spirit of the Elder Lizard",
  "미카엘의 도가니": "Mikael's Crucible",
  "노란색 장신구": "Yellow Trinket",
  "빨간색 장신구": "Red Trinket",
  "즈롯 차원문": "Zz'Rot Portal",
  "프로토타입 마공학 핵": "Prototype Hex Core",
  "마공학 핵 mk-1": "Hex Core mk-1",
  "마공학 핵 mk-2": "Hex Core mk-2",
  "완성형 마공학 핵": "Perfect Hex Core",
  "에그노그": "Eggnog",
  "티백": "Bag of Tea",
  "캔디 콘": "Candy Corn",
  "잠긴 무기 슬롯": "Locked Weapon Slot",
  "회오리 칼날": "Cyclonic Slicers",
  "유미봇": "YuumiBot",
  "광휘 역장": "Radiant Field",
  "스태틱의 검": "Statikk Sword",
  "사자의 비가": "Lioness's Lament",
  "개틀링 토끼 건": "Gatling Bunny-Guns",
  "타오르는 단궁": "Searing Shortbow",
  "절멸자": "The Annihilator",
  "전투 토끼 석궁": "Battle Bunny Crossbow",
  "귀여운 발사기": "UwU Blaster",
  "소용돌이 장갑": "Vortex Glove",
  "칼날 부메랑": "Blade-o-rang",
  "토끼 초강력 폭발": "Bunny Mega-Blast",
  "상어잡이 해양 기뢰": "Anti-Shark Sea Mine",
  "티.버": "T.I.B.B.E.R.S",
  "동물 지뢰": "Ani-Mines",
  "최후의 도시 대중교통": "Final City Transit",
  "메아리치는 박쥐칼날": "Echoing Batblades",
  "발자국 중독 장치": "Paw Print Poisoner",
  "얼음작렬 갑옷": "Iceblast Armor",
  "그치지 않는 폭풍": "Unceasing Cyclone",
  "유미봇_최종_최종": "YuumiBot_Final_FINAL",
  "폭발의 포옹": "Explosive Embrace",
  "프룸비스의 전기도축칼": "Prumbis's Electrocarver",
  "휘감는 빛": "Enveloping Light",
  "이중 깡충깡충 포화": "Double Bun-Bun Barrage",
  "진화한 불꽃 사격": "Evolved Embershot",
  "동물의 종말": "Animapocalypse",
  "토끼 프라임 거대 석궁": "Bunny Prime Ballista",
  "왕 귀여운 발사기": "OwO Blaster",
  "폭풍의 건틀릿": "Tempest's Gauntlet",
  "사중 부메랑": "Quad-o-rang",
  "고속 토끼 속사포": "Rapid Rabbit Raindown",
  "무한의 괴물 퇴치기": "Neverending Mobstomper",
  "티.버 (특.대.형 에디션)": "T.I.B.B.E.R.S (B.E.E.G Edition)",
  "징크스의 삼중 다이너마이트": "Jinx's Tri-Namite",
  "FC 급행열차": "FC Limited Express",
  "베인의 크로마칼날": "Vayne's Chromablades",
  "맨발 화학 물질 분사기": "Bearfoot Chem-Dispenser",
  "완전 빙결": "Deep Freeze",
  "야옹 야옹": "Meow Meow",
  "방패 타격": "Shield Slam",
  "음향의 물결": "Sound Wave",
  "족쇄 할퀴기": "Pillory Swipe",
  "강철 폭풍": "Steel Tempest",
  "촉수 후려치기": "Tentacle Slam",
  "날개 달린 단검": "Winged Dagger",
  "인도의 저주": "Guiding Hex",
  "토끼뜀": "Bunny Hop",
  "전투 고양이 총알 세례": "Battle Cat Barrage",
  "사자의 광명": "Light of the Lion",
  "동물 메아리": "Anima Echo",
  "포악한 베기": "Savage Slice",
  "떠도는 폭풍": "Wandering Storms",
  "곰의 강타": "Grizzly Smash",
  "연인의 도탄": "Lover's Ricochet",
  "고양된 저주": "Hopped-Up Hex",
  "당근 격돌": "Carrot Crash",
  "지배": "Domination",
  "감전": "Electrocute",
  "어둠의 수확": "Dark Harvest",
  "칼날비": "Hail of Blades",
  "비열한 한 방": "Cheap Shot",
  "피의 맛": "Taste of Blood",
  "돌발 일격": "Sudden Impact",
  "육감": "Sixth Sense",
  "섬뜩한 기념품": "Grisly Mementos",
  "깊은 와드": "Deep Ward",
  "보물 사냥꾼": "Treasure Hunter",
  "끈질긴 사냥꾼": "Relentless Hunter",
  "궁극의 사냥꾼": "Ultimate Hunter",
  "영감": "Inspiration",
  "빙결 강화": "Glacial Augment",
  "봉인 풀린 주문서": "Unsealed Spellbook",
  "선제공격": "First Strike",
  "마법공학 점멸기": "Hextech Flashtraption",
  "마법의 신발": "Magical Footwear",
  "환급": "Cash Back",
  "삼중 물약": "Triple Tonic",
  "시간 왜곡 물약": "Time Warp Tonic",
  "비스킷 배달": "Biscuit Delivery",
  "우주적 통찰력": "Cosmic Insight",
  "쾌속 접근": "Approach Velocity",
  "다재다능": "Jack Of All Trades",
  "정밀": "Precision",
  "집중 공격": "Press the Attack",
  "치명적 속도": "Lethal Tempo",
  "기민한 발놀림": "Fleet Footwork",
  "정복자": "Conqueror",
  "생명 흡수": "Absorb Life",
  "승전보": "Triumph",
  "침착": "Presence of Mind",
  "전설: 민첩함": "Legend: Alacrity",
  "전설: 가속": "Legend: Haste",
  "전설: 핏빛 길": "Legend: Bloodline",
  "최후의 일격": "Coup de Grace",
  "체력차 극복": "Cut Down",
  "최후의 저항": "Last Stand",
  "결의": "Resolve",
  "착취의 손아귀": "Grasp of the Undying",
  "여진": "Aftershock",
  "철거": "Demolish",
  "생명의 샘": "Font of Life",
  "보호막 강타": "Shield Bash",
  "사전 준비": "Conditioning",
  "재생의 바람": "Second Wind",
  "뼈 방패": "Bone Plating",
  "소생": "Revitalize",
  "불굴의 의지": "Unflinching",
  "마법": "Sorcery",
  "콩콩이 소환": "Summon Aery",
  "신비로운 유성": "Arcane Comet",
  "폭풍전사의 포효": "Stormraider's Surge",
  "죽음불꽃 손길": "Deathfire Touch",
  "액시옴 비전 마법사": "Axiom Arcanist",
  "마나순환 팔찌": "Manaflow Band",
  "빛의 망토": "Nimbus Cloak",
  "깨달음": "Transcendence",
  "기민함": "Celerity",
  "절대 집중": "Absolute Focus",
  "주문 작열": "Scorch",
  "물 위를 걷는 자": "Waterwalking",
  "폭풍의 결집": "Gathering Storm",
  "방어막": "Barrier",
  "고양": "Surge",
  "정화": "Cleanse",
  "점멸": "Flash",
  "도주": "Flee",
  "천리안": "Clairvoyance",
  "점화": "Ignite",
  "탈진": "Exhaust",
  "구축": "Fortify",
  "유체화": "Ghost",
  "회복": "Heal",
  "총명": "Clarity",
  "왕을 향해!": "To the King!",
  "포로 던지기": "Poro Toss",
  "결집": "Rally",
  "부활": "Revive",
  "강타": "Smite",
  "표식": "Mark",
  "진급": "Promote",
  "순간이동": "Teleport",
  "게임 시작 후 결정": "Placeholder",
  "TBD 및 공격-강타": "Placeholder and Attack-Smite",
  "강철의 솔라리 팬던트": "Locket of the Iron Solari",
  "치유 감소 아이템": "Grievous Wounds Items",
  "하드탱커": "Hard Tank",
  "유틸형 원거리 서포터": "Ranged Enchanter Support",
  "애니보다 팔이 긴 챔피언": "Champions with longer range than Annie",
  "아우렐리온솔": "Aurelion Sol",
  "문도박사": "Dr. Mundo",
  "자르반4세": "Jarvan IV",
  "리신": "Lee Sin",
  "마스터이": "Master Yi",
  "미스포츈": "Miss Fortune",
  "누누와윌럼프": "Nunu & Willump",
  "레나타글라스크": "Renata Glasc",
  "탐켄치": "Tahm Kench",
  "트위스티드페이트": "Twisted Fate",
  "신짜오": "Xin Zhao",
  "요정의부적": "Faerie Charm",
  "원기회복의구슬": "Rejuvenation Bead",
  "거인의허리띠": "Giant's Belt",
  "민첩성의망토": "Cloak of Agility",
  "방출의마법봉": "Blasting Wand",
  "사파이어수정": "Sapphire Crystal",
  "루비수정": "Ruby Crystal",
  "천갑옷": "Cloth Armor",
  "쇠사슬조끼": "Chain Vest",
  "마법무효화의망토": "Null-Magic Mantle",
  "잉걸불칼": "Emberknife",
  "B.F.대검": "B. F. Sword",
  "흑요석검": "Obsidian Edge",
  "증폭의고서": "Amplifying Tome",
  "흡혈의낫": "Vampiric Scepter",
  "도란의방패": "Doran's Shield",
  "도란의검": "Doran's Blade",
  "도란의반지": "Doran's Ring",
  "음전자망토": "Negatron Cloak",
  "쓸데없이큰지팡이": "Needlessly Large Rod",
  "암흑의인장": "Dark Seal",
  "수확의낫": "Cull",
  "도란의활": "Doran's Bow",
  "퀘스트:상단": "Quest: Top",
  "퀘스트:중단": "Quest: Mid",
  "퀘스트:하단": "Quest: Bot",
  "퀘스트:서포터": "Quest: Support",
  "퀘스트:정글": "Quest: Jungle",
  "새끼화염발톱": "Scorchclaw Pup",
  "새끼바람돌이": "Gustwalker Hatchling",
  "새끼이끼쿵쿵이": "Mosstomper Seedling",
  "전령의눈": "Eye of the Herald",
  "자르반1세의": "Jarvan I's",
  "도란의투구": "Doran's Helm",
  "상단공격로퀘스트": "Top Lane Quest",
  "중단공격로퀘스트": "Mid Lane Quest",
  "하단공격로퀘스트": "Bot Lane Quest",
  "서포터퀘스트": "Support Quest",
  "정글퀘스트": "Jungle Quest",
  "정글퀘스트보상": "Jungle Quest Reward",
  "중단공격로퀘스트보상": "Mid Lane Quest Reward",
  "하단공격로퀘스트보상": "Bot Lane Quest Reward",
  "서포터퀘스트보상": "Support Quest Reward",
  "강력순간이동(상단공격로퀘스트보상)": "Unleashed Teleport (Top Lane Quest Reward)",
  "상단공격로퀘스트보상": "Top Lane Quest Reward",
  "파멸의식고서": "Rite Of Ruin",
  "꽃피는새벽의검": "Sword of Blossoming Dawn",
  "관통탄환": "Penetrating Bullets",
  "이중갑옷": "Reinforced Armor",
  "파수꾼의눈": "Warden's Eye",
  "방탄양말": "Anti-tower Socks",
  "특이체질": "Phreakish Gusto",
  "슈퍼메크방어구": "Super Mech Armor",
  "슈퍼메크전력장": "Super Mech Power Field",
  "포탑방패": "Turret Plating",
  "구조물현상금": "Structure Bounty",
  "포탑강화": "Tower Power-Up",
  "상급귀환": "Enhanced Recall",
  "체력물약": "Health Potion",
  "귀환비활성화": "Disabled Recall",
  "굳건한의지의완전한비스킷": "Total Biscuit of Everlasting Will",
  "키르히아이스의파편": "Kircheis Shard",
  "강철인장": "Steel Sigil",
  "땅굴채굴기": "Tunneler",
  "빛나는티끌": "Glowing Mote",
  "충전형물약": "Refillable Potion",
  "부패물약": "Corrupting Potion",
  "수호자의부적": "Guardian's Amulet",
  "수호자의장막": "Guardian's Shroud",
  "수호자의뿔피리": "Guardian's Horn",
  "포로간식": "Poro-Snax",
  "제어와드": "Control Ward",
  "투명와드": "Stealth Ward",
  "슈렐리아의군가": "Shurelya's Battlesong",
  "강철의영약": "Elixir of Iron",
  "마법의영약": "Elixir of Sorcery",
  "분노의영약": "Elixir of Wrath",
  "카파주스": "Cappa Juice",
  "힘의주스": "Juice of Power",
  "활력의주스": "Juice of Vitality",
  "가속의주스": "Juice of Haste",
  "행운의주사위": "Lucky Dice",
  "향상된행운의주사위": "Enhanced Lucky Dice",
  "증강레벨": "Augment Level",
  "숙련의영약": "Elixir of Skill",
  "탐욕의영약": "Elixir of Avarice",
  "힘의영약": "Elixir of Force",
  "힘의밴들주스": "Bandle Juice of Power",
  "활력의밴들주스": "Bandle Juice of Vitality",
  "가속의밴들주스": "Bandle Juice of Haste",
  "추가능력치": "Stat Bonus",
  "전설전사아이템": "Legendary Fighter Item",
  "전설원거리딜러아이템": "Legendary Marksman Item",
  "전설암살자아이템": "Legendary Assassin Item",
  "전설마법사아이템": "Legendary Mage Item",
  "전설탱커아이템": "Legendary Tank Item",
  "전설서포터아이템": "Legendary Support Item",
  "프리즘아이템": "Prismatic Item",
  "모루교환권": "Anvil Voucher",
  "골드능력치모루교환권": "Gold Stat Anvil Voucher",
  "프리즘능력치모루교환권": "Prismatic Stat Voucher",
  "용기교환권": "Bravery Voucher",
  "끝없는절망": "Unending Despair",
  "어둠불꽃횃불": "Blackfire Torch",
  "케이닉루컨": "Kaenic Rookern",
  "황혼과새벽": "Dusk and Dawn",
  "악마사냥꾼의화살": "Fiendhunter Bolts",
  "끝없는갈망": "Endless Hunger",
  "실체화장비": "Actualizer",
  "마법광학장치C44": "Hexoptics C44",
  "원형질안전벨트": "Protoplasm Harness",
  "속삭이는머리띠": "Whispering Circlet",
  "악곡의왕관": "Diadem of Songs",
  "대천사의지팡이": "Archangel's Staff",
  "유령배회자": "Ghostcrawlers",
  "광전사의군화": "Berserker's Greaves",
  "탐욕의군화": "Gluttonous Greaves",
  "신속의장화": "Boots of Swiftness",
  "화학공학부패기": "Chemtech Putrifier",
  "마법사의신발": "Sorcerer's Shoes",
  "수호천사": "Guardian Angel",
  "무한의대검": "Infinity Edge",
  "윤탈야생화살": "Yun Tal Wildarrows",
  "필멸자의운명": "Mortal Reminder",
  "도미닉경의인사": "Lord Dominik's Regards",
  "아트마의심판": "Atma's Reckoning",
  "대천사의포옹": "Seraph's Embrace",
  "유령무희": "Phantom Dancer",
  "판금장화": "Plated Steelcaps",
  "지크의융합": "Zeke's Convergence",
  "스테락의도전": "Sterak's Gage",
  "광휘의검": "Sheen",
  "정령의형상": "Spirit Visage",
  "태양불꽃방패": "Sunfire Aegis",
  "공허의불길": "Void Immolation",
  "칠흑의양날도끼": "The Black Cleaver",
  "실험적마공학판": "Experimental Hexplate",
  "굶주린히드라": "Ravenous Hydra",
  "가시갑옷": "Thornmail",
  "루난의허리케인": "Runaan's Hurricane",
  "스태틱의단검": "Statikk Shiv",
  "라바돈의죽음모자": "Rabadon's Deathcap",
  "마법사의최후": "Wit's End",
  "고속연사포": "Rapid Firecannon",
  "밴시의장막": "Banshee's Veil",
  "군단의방패": "Aegis of the Legion",
  "기사의맹세": "Knight's Vow",
  "얼어붙은심장": "Frozen Heart",
  "헤르메스의발걸음": "Mercury's Treads",
  "수호자의보주": "Guardian's Orb",
  "내셔의이빨": "Nashor's Tooth",
  "라일라이의수정홀": "Rylai's Crystal Scepter",
  "혹한의손길": "Winter's Approach",
  "종말의겨울": "Fimbulwinter",
  "구인수의격노검": "Guinsoo's Rageblade",
  "공허의지팡이": "Void Staff",
  "헤르메스의시미터": "Mercurial Scimitar",
  "요우무의유령검": "Youmuu's Ghostblade",
  "란두인의예언": "Randuin's Omen",
  "마법공학총검": "Hextech Gunblade",
  "마법공학로켓벨트": "Hextech Rocketbelt",
  "몰락한왕의검": "Blade of The Ruined King",
  "맬모셔스의아귀": "Maw of Malmortius",
  "존야의모래시계": "Zhonya's Hourglass",
  "명석함의아이오니아장화": "Ionian Boots of Lucidity",
  "쇼진의창": "Spear of Shojin",
  "수호자의검": "Guardian's Blade",
  "수호자의망치": "Guardian's Hammer",
  "수호자의단검": "Guardian's Dirk",
  "강철의솔라리펜던트": "Locket of the Iron Solari",
  "가고일돌갑옷": "Gargoyle Stoneplate",
  "미카엘의축복": "Mikael's Blessing",
  "불타는향로": "Ardent Censer",
  "정수약탈자": "Essence Reaver",
  "망자의갑옷": "Dead Man's Plate",
  "거대한히드라": "Titanic Hydra",
  "밤의끝자락": "Edge of Night",
  "망령해적검": "Spectral Cutlass",
  "제국의명령": "Imperial Mandate",
  "대자연의힘": "Force of Nature",
  "황금뒤집개": "Golden Spatula",
  "지평선의초점": "Horizon Focus",
  "우주의추진력": "Cosmic Drive",
  "균열생성기": "Riftmaker",
  "밤의수확자": "Night Harvester",
  "악마의포옹": "Demonic Embrace",
  "부서진여왕의왕관": "Crown of the Shattered Queen",
  "폭풍쇄도": "Stormsurge",
  "은빛여명": "Silvermere Dawn",
  "죽음의무도": "Death's Dance",
  "화공펑크사슬검": "Chempunk Chainsword",
  "갈라진하늘": "Sundered Sky",
  "흐르는물의지팡이": "Staff of Flowing Water",
  "월석재생기": "Moonstone Renewer",
  "헬리아의메아리": "Echoes of Helia",
  "발걸음분쇄기": "Stridebreaker",
  "신성한파괴자": "Divine Sunderer",
  "리안드리의고뇌": "Liandry's Anguish",
  "루덴의메아리": "Luden's Echo",
  "영겁의지팡이": "Rod of Ages",
  "얼어붙은건틀릿": "Iceborn Gauntlet",
  "공허한광휘": "Hollow Radiance",
  "해신작쇼": "Jak'Sho, The Protean",
  "광휘의미덕": "Radiant Virtue",
  "크라켄학살자": "Kraken Slayer",
  "불멸의철갑궁": "Immortal Shieldbow",
  "나보리명멸검": "Navori Flickerblade",
  "징수의총": "The Collector",
  "드락사르의황혼검": "Duskblade of Draktharr",
  "자객의발톱": "Prowler's Claw",
  "세릴다의원한": "Serylda's Grudge",
  "독사의송곳니": "Serpent's Fang",
  "원칙의원형낫": "Axiom Arc",
  "불경한히드라": "Profane Hydra",
  "증오의사슬": "Anathema's Chains",
  "우글렛의마녀모자": "Wooglet's Witchcap",
  "죽음의검": "Deathblade",
  "적응형투구": "Adaptive Helm",
  "흑요석양날도끼": "Obsidian Cleaver",
  "핏빛칼날": "Sanguine Blade",
  "룬글레이브": "Runeglaive",
  "다용도도구": "Multitool",
  "심연의가면": "Abyssal Mask",
  "미니언해체분석기": "Minion Dematerializer",
  "추적자의팔목보호대": "Seeker's Armguard",
  "부서진팔목보호대": "Shattered Armguard",
  "약간신비한신발": "Slightly Magical Footwear",
  "지배자의피갑옷": "Overlord's Bloodmail",
  "운명의재": "Fated Ashes",
  "공생형밑창": "Symbiotic Soles",
  "축복의성배": "Chalice of Blessing",
  "하나된영혼": "Synchronized Souls",
  "생명의샘펜던트": "Lifewell Pendant",
  "얼음방패": "Glacial Buckler",
  "최후의속삭임": "Last Whisper",
  "메자이의영혼약탈자": "Mejai's Soulstealer",
  "탐식의망치": "Phage",
  "온기가필요한자의도끼": "Hearthbound Axe",
  "비상의월갑": "Winged Moonplate",
  "여신의눈물": "Tear of the Goddess",
  "덤불조끼": "Bramble Vest",
  "파수꾼의갑옷": "Warden's Mail",
  "워모그의갑옷": "Warmog's Armor",
  "열정의검": "Zeal",
  "과거아이템": "Deprecated item",
  "악마의마법서": "Fiendish Codex",
  "에테르환영": "Aether Wisp",
  "금지된우상": "Forbidden Idol",
  "기동력의장화": "Boots of Mobility",
  "처형인의대검": "Executioner's Calling",
  "죽음불꽃손아귀": "Deathfire Grasp",
  "신성의검": "Sword of the Divine",
  "콜필드의전투망치": "Caulfield's Warhammer",
  "톱날단검": "Serrated Dirk",
  "수은장식띠": "Quicksilver Sash",
  "정찰병의새총": "Scout's Slingshot",
  "마법공학교류발전기": "Hextech Alternator",
  "기괴한가면": "Haunting Guise",
  "불멸의길": "Immortal Path",
  "핏빛명석함": "Crimson Lucidity",
  "건메탈군화": "Gunmetal Greaves",
  "사슬끈분쇄자": "Chainlaced Crushers",
  "무장진격": "Armored Advance",
  "주문투척자의신발": "Spellslinger's Shoes",
  "영원한전진": "Forever Forward",
  "그림자검": "Umbral Glaive",
  "망령의두건": "Spectre's Cowl",
  "비전탐지기": "Arcane Sweeper",
  "광휘의특이점": "Lucent Singularity",
  "망원형개조": "Farsight Alteration",
  "예언자의렌즈": "Oracle Lens",
  "작은파티선물": "Small Party Favor",
  "파티선물": "Party Favor",
  "칼리스타의칠흑의창": "Kalista's Black Spear",
  "수정팔보호구": "Crystalline Bracer",
  "사라진양피지": "Lost Chapter",
  "억겁의카탈리스트": "Catalyst of Aeons",
  "주문도둑의검": "Spellthief's Edge",
  "얼음송곳니": "Frostfang",
  "얼음정수의파편": "Shard of True Ice",
  "강철어깨보호대": "Steel Shoulderguards",
  "룬강철어깨갑옷": "Runesteel Spaulders",
  "화이트록의갑옷": "Pauldrons of Whiterock",
  "고대유물방패": "Relic Shield",
  "타곤산의방패": "Targon's Buckler",
  "타곤산의방벽": "Bulwark of the Mountain",
  "영혼의낫": "Spectral Sickle",
  "해로윙초승달낫": "Harrowing Crescent",
  "검은안개낫": "Black Mist Scythe",
  "세계지도집": "World Atlas",
  "룬나침반": "Runic Compass",
  "세계의결실": "Bounty of Worlds",
  "천상의이의": "Celestial Opposition",
  "꿈생성기": "Dream Maker",
  "자자크의세계가시": "Zaz'Zak's Realmspike",
  "태양의썰매": "Solstice Sleigh",
  "피의노래": "Bloodsong",
  "<rarityLegendary>가차없는포격</rarityLegendary><br><subtitleLeft><silver>바다뱀은화500닢</silver></subtitleLeft>": "<rarityLegendary>Fire at Will</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "<rarityLegendary>죽음의여신</rarityLegendary><br><subtitleLeft><silver>바다뱀은화500닢</silver></subtitleLeft>": "<rarityLegendary>Death's Daughter</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "<rarityLegendary>사기진작</rarityLegendary><br><subtitleLeft><silver>바다뱀은화500닢</silver></subtitleLeft>": "<rarityLegendary>Raise Morale</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>",
  "망각의구": "Oblivion Orb",
  "핏빛저주": "Bloodletter's Curse",
  "죄악포식자": "Sin Eater",
  "번개끈": "Lightning Braid",
  "얼어붙은망치": "Frozen Mallet",
  "무언의서약": "Wordless Promise",
  "지옥불손도끼": "Hellfire Hatchet",
  "활력증진의펜던트": "Innervating Locket",
  "흑강철발톱": "Darksteel Talons",
  "불사대마왕의왕관": "Demon King's Crown",
  "용암의방패": "Shield of Molten Stone",
  "별빛밤망토": "Cloak of Starry Night",
  "엔트로피의힘": "Force Of Entropy",
  "핏빛선물": "Sanguine Gift",
  "일라이자의기적": "Eleisa's Miracle",
  "승천의부적": "Talisman Of Ascension",
  "터보화공탱크": "Turbo Chemtank",
  "쌍둥이가면": "Twin Mask",
  "마공화살동료": "Hexbolt Companion",
  "사신의대가": "Reaper's Toll",
  "신기루검": "Mirage Blade",
  "도박꾼의칼날": "Gambler's Blade",
  "현실균열": "Reality Fracture",
  "혈마법사의투구": "Hemomancer's Helm",
  "창공의서약": "Empyrean Promise",
  "용의심장": "Dragonheart",
  "룬조각기": "Runecarver",
  "잔혹행위": "Cruelty",
  "달빛마법검": "Moonflair Spellblade",
  "폭발의구": "Detonation Orb",
  "섭정시해": "Regicide",
  "킨코우십수": "Kinkou Jitte",
  "화염술사의망토": "Pyromancer's Cloak",
  "번개막대": "Lightning Rod",
  "다이아몬드창": "Diamond-Tipped Spear",
  "황혼의끝자락": "Twilight's Edge",
  "블랙홀건틀릿": "Black Hole Gauntlet",
  "조종의손아귀": "Puppeteer",
  "역병의보석": "Blighting Jewel",
  "신록의장벽": "Verdant Barrier",
  "흡수의시선": "Leeching Leer",
  "감시하는와드석": "Watchful Wardstone",
  "고무의와드석": "Stirring Wardstone",
  "밴들유리거울": "Bandleglass Mirror",
  "경계의와드석": "Vigilant Wardstone",
  "체력바색칠:파랑": "Healthbar Splash: Blue",
  "체력바색칠:주황": "Healthbar Splash: Orange",
  "체력바색칠:초록": "Healthbar Splash: Green",
  "체력바색칠:분홍": "Healthbar Splash: Pink",
  "체력바청소:색상초기화": "Healthbar Cleanup: Reset Color",
  "체력바색칠:무지개": "Healthbar Splash: Rainbow",
  "강철가시채찍": "Ironspike Whip",
  "베이가의승천의부적": "Veigar's Talisman of Ascension",
  "리안드리의고통": "Liandry's Torment",
  "바미의불씨": "Bami's Cinder",
  "절정의화살": "Noonquiver",
  "분노의칼": "Rageknife",
  "라코어의방패": "Shield of the Rakkor",
  "전방정찰": "Scouting Ahead",
  "갱플랭크Placeholder": "Gangplank Placeholder",
  "속도의장화": "Boots of Speed",
  "사냥꾼의마체테": "Hunter's Machete",
  "싸움꾼의장갑": "Brawler's Gloves",
  "마나물약": "Mana Potion",
  "원기회복의완전한비스킷": "Total Biscuit of Rejuvenation",
  "불굴의영약": "Elixir of Fortitude",
  "민첩의영약": "Elixir of Agility",
  "지능의영약": "Elixir of Brilliance",
  "수정플라스크": "Crystalline Flask",
  "예언자의영약": "Oracle's Elixir",
  "투명감지와드": "Vision Ward",
  "시야와드": "Sight Ward",
  "루비시야석": "Ruby Sightstone",
  "탐험가의와드": "Explorer's Ward",
  "심연의홀": "Abyssal Scepter",
  "아트마의창": "Atma's Impaler",
  "수호자카탈리스트": "Catalyst the Protector",
  "쌍둥이그림자": "Twin Shadows",
  "빙하의장막": "Glacial Shroud",
  "조화의성배": "Chalice of Harmony",
  "마나의보주": "Mana Manipulator",
  "닌자의신발": "Ninja Tabi",
  "스타크의열정": "Stark's Fervor",
  "용맹의징표": "Emblem of Valor",
  "저항공성기": "Ohmwrecker",
  "지휘관의깃발": "Banner of Command",
  "영혼의갑옷": "Soul Shroud",
  "태양불꽃망토": "Sunfire Cape",
  "슈렐리아의몽상": "Shurelya's Reverie",
  "태양불꽃망토무더기": "Stack of Sunfire Capes",
  "탐욕의검": "Avarice Blade",
  "현자의돌": "Philosopher's Stone",
  "행운피크": "Lucky Pick",
  "마드레드의갈퀴손": "Madred's Razors",
  "룬방벽": "Runic Bulwark",
  "마드레드의피갈퀴손": "Madred's Bloodrazor",
  "역병의비수": "Malady",
  "황금의심장": "Heart of Gold",
  "레비아탄갑옷": "Leviathan",
  "비술의검": "Sword of the Occult",
  "빌지워터해적검": "Bilgewater Cutlass",
  "마법공학리볼버": "Hextech Revolver",
  "고대인의의지": "Will of the Ancients",
  "리글의랜턴": "Wriggle's Lantern",
  "야생의섬광": "Feral Flare",
  "슈세이의마나통": "Shushei's Mana Jug",
  "이온충격기": "Ionic Spark",
  "망령의영혼": "Spirit of the Spectral Wraith",
  "고대골렘의영혼": "Spirit of the Ancient Golem",
  "도마뱀장로의영혼": "Spirit of the Elder Lizard",
  "미카엘의도가니": "Mikael's Crucible",
  "노란색장신구": "Yellow Trinket",
  "빨간색장신구": "Red Trinket",
  "즈롯차원문": "Zz'Rot Portal",
  "프로토타입마공학핵": "Prototype Hex Core",
  "마공학핵mk-1": "Hex Core mk-1",
  "마공학핵mk-2": "Hex Core mk-2",
  "완성형마공학핵": "Perfect Hex Core",
  "캔디콘": "Candy Corn",
  "잠긴무기슬롯": "Locked Weapon Slot",
  "회오리칼날": "Cyclonic Slicers",
  "광휘역장": "Radiant Field",
  "스태틱의검": "Statikk Sword",
  "사자의비가": "Lioness's Lament",
  "개틀링토끼건": "Gatling Bunny-Guns",
  "타오르는단궁": "Searing Shortbow",
  "전투토끼석궁": "Battle Bunny Crossbow",
  "귀여운발사기": "UwU Blaster",
  "소용돌이장갑": "Vortex Glove",
  "칼날부메랑": "Blade-o-rang",
  "토끼초강력폭발": "Bunny Mega-Blast",
  "상어잡이해양기뢰": "Anti-Shark Sea Mine",
  "동물지뢰": "Ani-Mines",
  "최후의도시대중교통": "Final City Transit",
  "메아리치는박쥐칼날": "Echoing Batblades",
  "발자국중독장치": "Paw Print Poisoner",
  "얼음작렬갑옷": "Iceblast Armor",
  "그치지않는폭풍": "Unceasing Cyclone",
  "폭발의포옹": "Explosive Embrace",
  "프룸비스의전기도축칼": "Prumbis's Electrocarver",
  "휘감는빛": "Enveloping Light",
  "이중깡충깡충포화": "Double Bun-Bun Barrage",
  "진화한불꽃사격": "Evolved Embershot",
  "동물의종말": "Animapocalypse",
  "토끼프라임거대석궁": "Bunny Prime Ballista",
  "왕귀여운발사기": "OwO Blaster",
  "폭풍의건틀릿": "Tempest's Gauntlet",
  "사중부메랑": "Quad-o-rang",
  "고속토끼속사포": "Rapid Rabbit Raindown",
  "무한의괴물퇴치기": "Neverending Mobstomper",
  "티.버(특.대.형에디션)": "T.I.B.B.E.R.S (B.E.E.G Edition)",
  "징크스의삼중다이너마이트": "Jinx's Tri-Namite",
  "FC급행열차": "FC Limited Express",
  "베인의크로마칼날": "Vayne's Chromablades",
  "맨발화학물질분사기": "Bearfoot Chem-Dispenser",
  "완전빙결": "Deep Freeze",
  "야옹야옹": "Meow Meow",
  "방패타격": "Shield Slam",
  "음향의물결": "Sound Wave",
  "족쇄할퀴기": "Pillory Swipe",
  "강철폭풍": "Steel Tempest",
  "촉수후려치기": "Tentacle Slam",
  "날개달린단검": "Winged Dagger",
  "인도의저주": "Guiding Hex",
  "전투고양이총알세례": "Battle Cat Barrage",
  "사자의광명": "Light of the Lion",
  "동물메아리": "Anima Echo",
  "포악한베기": "Savage Slice",
  "떠도는폭풍": "Wandering Storms",
  "곰의강타": "Grizzly Smash",
  "연인의도탄": "Lover's Ricochet",
  "고양된저주": "Hopped-Up Hex",
  "당근격돌": "Carrot Crash",
  "어둠의수확": "Dark Harvest",
  "비열한한방": "Cheap Shot",
  "피의맛": "Taste of Blood",
  "돌발일격": "Sudden Impact",
  "섬뜩한기념품": "Grisly Mementos",
  "깊은와드": "Deep Ward",
  "보물사냥꾼": "Treasure Hunter",
  "끈질긴사냥꾼": "Relentless Hunter",
  "궁극의사냥꾼": "Ultimate Hunter",
  "빙결강화": "Glacial Augment",
  "봉인풀린주문서": "Unsealed Spellbook",
  "마법공학점멸기": "Hextech Flashtraption",
  "마법의신발": "Magical Footwear",
  "삼중물약": "Triple Tonic",
  "시간왜곡물약": "Time Warp Tonic",
  "비스킷배달": "Biscuit Delivery",
  "우주적통찰력": "Cosmic Insight",
  "쾌속접근": "Approach Velocity",
  "집중공격": "Press the Attack",
  "치명적속도": "Lethal Tempo",
  "기민한발놀림": "Fleet Footwork",
  "생명흡수": "Absorb Life",
  "전설:민첩함": "Legend: Alacrity",
  "전설:가속": "Legend: Haste",
  "전설:핏빛길": "Legend: Bloodline",
  "최후의일격": "Coup de Grace",
  "체력차극복": "Cut Down",
  "최후의저항": "Last Stand",
  "착취의손아귀": "Grasp of the Undying",
  "생명의샘": "Font of Life",
  "보호막강타": "Shield Bash",
  "사전준비": "Conditioning",
  "재생의바람": "Second Wind",
  "뼈방패": "Bone Plating",
  "불굴의의지": "Unflinching",
  "콩콩이소환": "Summon Aery",
  "신비로운유성": "Arcane Comet",
  "폭풍전사의포효": "Stormraider's Surge",
  "죽음불꽃손길": "Deathfire Touch",
  "액시옴비전마법사": "Axiom Arcanist",
  "마나순환팔찌": "Manaflow Band",
  "빛의망토": "Nimbus Cloak",
  "절대집중": "Absolute Focus",
  "주문작열": "Scorch",
  "물위를걷는자": "Waterwalking",
  "폭풍의결집": "Gathering Storm",
  "왕을향해!": "To the King!",
  "포로던지기": "Poro Toss",
  "게임시작후결정": "Placeholder",
  "TBD및공격-강타": "Placeholder and Attack-Smite",
  "강철의솔라리팬던트": "Locket of the Iron Solari",
  "치유감소아이템": "Grievous Wounds Items",
  "유틸형원거리서포터": "Ranged Enchanter Support",
  "애니보다팔이긴챔피언": "Champions with longer range than Annie"
};

var LINE_EN_MAP = {
  "탑": "Top",
  "정글": "Jungle",
  "미드": "Mid",
  "원딜": "ADC",
  "바텀": "ADC",
  "서폿": "Support",
  "서포터": "Support",
  "전체": "All"
};

var EN_TO_KO_MAP = {};
for (var koName in CHAMP_EN_MAP) {
    EN_TO_KO_MAP[CHAMP_EN_MAP[koName].toLowerCase()] = koName;
}
